apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grug-config
data:
{{- $files := .Files -}}
{{- with .Values.config.masterConfig }}
  grug.yaml: |
    {{- $files.Get . | nindent 4 -}}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-commands
data:
{{- $files := .Files -}}
{{- $globPat := printf "%s/*.yaml" (.Values.config.commands | trimSuffix "/") }}
{{ (.Files.Glob $globPat).AsConfig | indent 2 }}
