apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grug.fullname" . }}
  labels:
    {{- include "grug.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "grug.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grug.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Release.Name }}-config-volume
              mountPath: "/etc/grug"
            - name: {{ .Release.Name }}-command-volume
              mountPath: "/etc/grug/commands"
          ports:
            - name: http
              containerPort: 5700
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
            - name: "GRUG_CONFIG_FILE"
              value: "/etc/grug/grug.yaml"
            - name: "GRUG_DISCORD_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: "DISCORD_BOT_TOKEN"
      volumes:
        - name: {{ .Release.Name }}-config-volume
          configMap:
            name: {{ .Release.Name }}-grug-config
        - name: {{ .Release.Name }}-command-volume
          configMap:
            name: {{ .Release.Name }}-commands
